In [3]:
import sys
print(sys.executable)

/opt/anaconda3/envs/myproj/bin/python

In [4]:
import kagglehub
print("kagglehub version:", kagglehub.__version__)

kagglehub version: 0.3.12

In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ak0212/china-cancer-patient-records")

print("Path to dataset files:", path)

Path to dataset files: /Users/f/.cache/kagglehub/datasets/ak0212/china-cancer-patient-records/versions/1

In [6]:
import os

data_dir = "/Users/f/.cache/kagglehub/datasets/ak0212/china-cancer-patient-records/versions/1"
print(os.listdir(data_dir))

['china_cancer_patients_synthetic.csv']

In [7]:
import pandas as pd

df = pd.read_csv(f"{data_dir}/china_cancer_patients_synthetic.csv")

In [11]:
# Show unique tumor types
print("Unique tumor types:", df['TumorType'].unique())
print("Number of unique tumor types:", df['TumorType'].nunique())

Unique tumor types: ['Lung' 'Breast' 'Stomach' 'Liver' 'Colorectal' 'Cervical']
Number of unique tumor types: 6

In [10]:
# Form (Zeilen, Spalten)
print("Shape:", df.shape)

# Erste 5 Zeilen
display(df.head())

# Datentypen & Nicht-Null-Zahlen
print(df.info())

# Grundlegende Statistik (numerisch + kategorisch)
display(df.describe(include="all"))

Shape: (10000, 20)

,PatientID,Gender,Age,Province,Ethnicity,TumorType,CancerStage,DiagnosisDate,TumorSize,Metastasis,TreatmentType,SurgeryDate,ChemotherapySessions,RadiationSessions,SurvivalStatus,FollowUpMonths,SmokingStatus,AlcoholUse,GeneticMutation,Comorbidities
0,CHN-00001,Male,32,Hunan,Han,Lung,I,2010-07-24,8.2,No,Radiation,2010-08-24,0,23,Alive,44,Current,NaN,NaN,NaN
1,CHN-00002,Male,66,Sichuan,Han,Lung,IV,2015-01-03,9.5,Yes,Chemotherapy,2015-03-24,11,0,Deceased,57,Never,Occasional,EGFR,"Hepatitis B, Hypertension"
2,CHN-00003,Other,26,Guangdong,Han,Lung,III,2022-03-26,9.3,Yes,Surgery,2022-07-14,0,0,Alive,40,Former,NaN,NaN,NaN
3,CHN-00004,Other,35,Anhui,Uyghur,Breast,III,2019-06-19,7.7,No,Surgery,2019-08-27,0,0,Deceased,45,Never,Occasional,KRAS,NaN
4,CHN-00005,Male,32,Guangdong,Han,Stomach,II,2012-02-07,7.3,No,Chemotherapy,NaN,4,0,Alive,42,Never,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PatientID             10000 non-null  object
 1   Gender                10000 non-null  object
 2   Age                   10000 non-null  int64
 3   Province              10000 non-null  object
 4   Ethnicity             10000 non-null  object
 5   TumorType             10000 non-null  object
 6   CancerStage           10000 non-null  object
 7   DiagnosisDate         10000 non-null  object
 8   TumorSize             10000 non-null  float64
 9   Metastasis            10000 non-null  object
 10  TreatmentType         10000 non-null  object
 11  SurgeryDate           4327 non-null   object
 12  ChemotherapySessions  10000 non-null  int64
 13  RadiationSessions     10000 non-null  int64
 14  SurvivalStatus        10000 non-null  object
 15  FollowUpMonths        10000 non-null  int64
 16  SmokingStatus         10000 non-null  object
 17  AlcoholUse            4079 non-null   object
 18  GeneticMutation       2800 non-null   object
 19  Comorbidities         6285 non-null   object
dtypes: float64(1), int64(4), object(15)
memory usage: 1.5+ MB
None

,PatientID,Gender,Age,Province,Ethnicity,TumorType,CancerStage,DiagnosisDate,TumorSize,Metastasis,TreatmentType,SurgeryDate,ChemotherapySessions,RadiationSessions,SurvivalStatus,FollowUpMonths,SmokingStatus,AlcoholUse,GeneticMutation,Comorbidities
count,10000,10000,10000.000000,10000,10000,10000,10000,10000,10000.000000,10000,10000,4327,10000.0000,10000.000000,10000,10000.000000,10000,4079,2800,6285
unique,10000,3,NaN,13,6,6,4,4383,NaN,2,5,2915,NaN,NaN,2,NaN,3,2,3,9
top,CHN-00001,Female,NaN,Guangdong,Han,Lung,II,2016-11-08,NaN,No,Chemotherapy,2012-09-23,NaN,NaN,Alive,NaN,Never,Occasional,EGFR,Hypertension
freq,1,3371,NaN,1841,9110,2561,2971,8,NaN,7301,2072,5,NaN,NaN,7790,NaN,5011,3127,1389,1514
mean,NaN,NaN,51.600200,NaN,NaN,NaN,NaN,NaN,6.339040,NaN,NaN,NaN,3.9990,3.046400,NaN,30.432800,NaN,NaN,NaN,NaN
std,NaN,NaN,19.705608,NaN,NaN,NaN,NaN,NaN,2.234999,NaN,NaN,NaN,6.2036,7.301505,NaN,17.162545,NaN,NaN,NaN,NaN
min,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN,0.500000,NaN,NaN,NaN,0.0000,0.000000,NaN,1.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,35.000000,NaN,NaN,NaN,NaN,NaN,4.800000,NaN,NaN,NaN,0.0000,0.000000,NaN,16.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,51.000000,NaN,NaN,NaN,NaN,NaN,6.400000,NaN,NaN,NaN,0.0000,0.000000,NaN,31.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,69.000000,NaN,NaN,NaN,NaN,NaN,7.900000,NaN,NaN,NaN,8.0000,0.000000,NaN,45.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,85.000000,NaN,NaN,NaN,NaN,NaN,14.200000,NaN,NaN,NaN,20.0000,30.000000,NaN,60.000000,NaN,NaN,NaN,NaN

In [12]:
import os

# Create a new folder for saving the data
output_dir = "./data"
os.makedirs(output_dir, exist_ok=True)

# Save the first 20 records to a CSV file
output_file = f"{output_dir}/first_20_records.csv"
df.head(20).to_csv(output_file, index=False)

print(f"First 20 records saved to: {output_file}")

First 20 records saved to: ./data/first_20_records.csv